nexi_index:
    path:     /nexi/{id}
    defaults: { _controller: SergioTropeaNexiBundle:Default:index }

nexi_abort:
    path:     /nexi/abort/{id}
    defaults: { _controller: SergioTropeaNexiBundle:Default:abort }

nexi_response:
    path:     /nexi/response/{id}
    defaults: { _controller: SergioTropeaNexiBundle:Default:response }