<?php

namespace SergioTropea\NexiBundle\Repository;

/**
 * NexiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NexiRepository extends \Doctrine\ORM\EntityRepository
{
}
